### ISSUE TITLE
GEOINT Services Task List

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/project-geohsv-2017#23]
**ATO**
- [x] Finish fixes from SonarQube - Alex
- [x] Satisfy ThreadFix scans (Fortify, etc.) - Josh access and replicate (?)
- [x] Address logging (e.g. user log for request/response from web services)

**GeoAxis** - Richard/Alex/Josh?
- [x] Get OSH talking to GeoAxis
- [ ] Fix Name recognition on OSH - Alex and Josh with Richard
- [ ] Test at NGA - Richard and Josh

**GeoNode** - Richard/Josh/Alex/Mathieu - timing?
- [x] Meet with Richard/Chris T. on status and directions
- [ ] Get familiar with how GeoNode works?  How does current community do styling?
- [ ] Fulfill needs from Boundless ? (what was this?)
- [ ] Default styling for certain data types - Mathieu
- [ ] Adding map with styling (support for SLD?) - Alex/Mathieu
- [ ] Finish/demonstrate

**Real Sensors**
- [ ] Find real sensors to integrate in .mil and UC domains
- [ ] Look at issue of sensor status (heartbeat) for SOS-T Clients

**Army SIF**
- [ ] ~~Finish initial MASBUS - OSH Integration~~
- [ ] Add insertObservation - Alex
- [ ] ~~Add insertSensor (v2.0) - Alex~~
- [ ] Test / demonstrate interoperability
- [ ] Help MASBUS migrate to SensorML 2.0
- [ ] Help MASBUS add getResult support
- [ ] Work on ISA to OSH bridge

**Comment by alexrobin** [comment]
Project ended

**Comment by Sam-Bolling** [comment]
Good afternoon, Alex and Mike.  Are there more details regarding the ending of this project?  Can you link to the new issue that was transferred to the opensensorhub/osh-core?

@alexrobin @mikebotts 

Respectfully,

Sam
bolling.samuel@gmail.com
703.203.5281
